In [1]:
import sys
sys.path.append('..')

In [2]:
import sparsity_pattern as spat
import scipy.sparse
import numpy as np
from typing import List

def print_matrix(idx: List[List[int]], n_rows, n_cols):
    # convert to matrix
    if len(idx):
        mat = scipy.sparse.lil_matrix((n_rows, n_cols), dtype=np.int64)
        idx_rows, idx_cols = np.array(idx)[:, 0], np.array(idx)[:, 1]
        mat[idx_rows, idx_cols] = 1
    # print
    print("Sparsity Pattern:")
    print(idx)
    if len(idx):
        print("Matrix:")
        print(mat.todense())

# `'dense'` (all elements)
The sparsity pattern for a dense matrix contains all possible row/column combinations.

In [3]:
# quadratic dense matrix
idx = spat.get("dense", 3)

print_matrix(idx, 3, 3)

Sparsity Pattern:
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
# 2x3 dense matrix
idx = spat.get("dense", r=2, c=3)

print_matrix(idx, 2, 3)

Sparsity Pattern:
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]
Matrix:
[[1 1 1]
 [1 1 1]]


In [5]:
# 4x3 dense matrix
idx = spat.get("dense", 4, 3)

print_matrix(idx, 4, 3)

Sparsity Pattern:
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2)]
Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


# `'diag'` (Diagonal elements only)
A diagonal matrix has only elements $e_{ii}$

$$
\begin{bmatrix}
e_{11} & 0 & \cdots & 0\\
0 & e_{22} & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & e_{nn}\\
\end{bmatrix}
$$

The diagonal matrix usually refers to quadratic matrices

In [6]:
idx = spat.get("diag", 3)

print_matrix(idx, 3, 3)

Sparsity Pattern:
[(0, 0), (1, 1), (2, 2)]
Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


However, we can generate bigger matrices too

In [7]:
# two empty columns
print_matrix(idx, 3, 5)

Sparsity Pattern:
[(0, 0), (1, 1), (2, 2)]
Matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [8]:
# two empty rows
print_matrix(idx, 5, 3)

Sparsity Pattern:
[(0, 0), (1, 1), (2, 2)]
Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]]


In [9]:
# one row and one column is empty
print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 0), (1, 1), (2, 2)]
Matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 0]]


# `'nodiag'` (Dense without diagonal elements)
A dense matrix without the diagonal elements

$$
\begin{bmatrix}
0 & e_{12} & e_{13} & \cdots & e_{1n}\\
e_{21} & 0 & e_{23} & \cdots & e_{2n}\\
e_{31} & e_{32} & 0 & \cdots & e_{3n}\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
e_{n1} & e_{n2} & e_{n3} & \cdots & 0\\
\end{bmatrix}
$$

A sparse matrix could be a dense matrix without diagonal elements.

In [10]:
idx = spat.get("nodiag", 4)

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 1), (0, 2), (0, 3), (1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 3), (3, 0), (3, 1), (3, 2)]
Matrix:
[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


In [11]:
idx = spat.get("nodiag", 3, 5)

print_matrix(idx, 3, 5)

Sparsity Pattern:
[(0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 2), (1, 3), (1, 4), (2, 0), (2, 1), (2, 3), (2, 4)]
Matrix:
[[0 1 1 1 1]
 [1 0 1 1 1]
 [1 1 0 1 1]]


In [12]:
idx = spat.get("nodiag", 5, 3)

print_matrix(idx, 5, 3)

Sparsity Pattern:
[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (3, 0), (3, 1), (3, 2), (4, 0), (4, 1), (4, 2)]
Matrix:
[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [1 1 1]]


# `'block'` (Block-diagonal elements only)
Block-diagonal matrices should be quadratic, and the matrix dimension should be a multiple of the block size.

In [13]:
n_block_size = 2
n_matrix_size = n_block_size * 3

idx = spat.get('block', n_matrix_size, n_block_size)

print_matrix(idx, n_matrix_size, n_matrix_size)

Sparsity Pattern:
[(0, 0), (0, 1), (1, 0), (1, 1), (2, 2), (2, 3), (3, 2), (3, 3), (4, 4), (4, 5), (5, 4), (5, 5)]
Matrix:
[[1 1 0 0 0 0]
 [1 1 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 1 1]
 [0 0 0 0 1 1]]


Like with `diag`, we can increase the matrix size with the result that full rows and/or columns are empty, e.g., 

In [14]:
print_matrix(idx, n_matrix_size, n_matrix_size + 3)

Sparsity Pattern:
[(0, 0), (0, 1), (1, 0), (1, 1), (2, 2), (2, 3), (3, 2), (3, 3), (4, 4), (4, 5), (5, 4), (5, 5)]
Matrix:
[[1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0]
 [0 0 0 0 1 1 0 0 0]]


Our algorithms allows not perfect splits, e.g., a 5x5 matrix has only space for two 2x2 blocks so that the last block is adjusted to an 1x1 block.

In [15]:
n_block_size = 2
n_matrix_size = 5

idx = spat.get('block', n_matrix_size, n_block_size)

print_matrix(idx, n_matrix_size, n_matrix_size)

Sparsity Pattern:
[(0, 0), (0, 1), (1, 0), (1, 1), (2, 2), (2, 3), (3, 2), (3, 3), (4, 4)]
Matrix:
[[1 1 0 0 0]
 [1 1 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 1]]


The adjustment will be the next biggest block

In [16]:
n_block_size = 3
n_matrix_size = 5

idx = spat.get('block', n_matrix_size, n_block_size)

print_matrix(idx, n_matrix_size, n_matrix_size)

Sparsity Pattern:
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2), (3, 3), (3, 4), (4, 3), (4, 4)]
Matrix:
[[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 1]
 [0 0 0 1 1]]


We can also create different block sizes

In [17]:
n_block_sizes = [3, 1, 2]
n_matrix_size = 10

idx = spat.get('block', n_matrix_size, n_block_sizes)

print_matrix(idx, n_matrix_size, n_matrix_size)

Sparsity Pattern:
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2), (3, 3), (4, 4), (4, 5), (5, 4), (5, 5), (6, 6), (6, 7), (6, 8), (7, 6), (7, 7), (7, 8), (8, 6), (8, 7), (8, 8), (9, 9)]
Matrix:
[[1 1 1 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


# `'circle'`
The name of this sparsity pattern has the following idea.

In [18]:
idx = spat.get('circle', 4)

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 3), (1, 0), (2, 1), (3, 2)]
Matrix:
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


If we multiply the sparse matrix $W$ with a vector $s_1=(1, 0, 0, 0)$,
the next state would be $s_2=(0, 1, 0, 0)$,
$s_3=(0, 0, 1, 0)$, $s_4=(0, 0, 0, 1)$, and finally $s_{1+4}=(1, 0, 0, 0)$.
In other word, the information travelled full circle back to its origin.

We can add more offsets (i.e., the information would travel faster)

In [19]:
idx = spat.get('circle', 4, offsets=[1, 2])

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 2), (0, 3), (1, 0), (1, 3), (2, 0), (2, 1), (3, 1), (3, 2)]
Matrix:
[[0 0 1 1]
 [1 0 0 1]
 [1 1 0 0]
 [0 1 1 0]]


If the number of offsets is $n-1$, `'circle'` is equivalent to the quadratic `'nodiag'`

In [20]:
idx = spat.get('circle', n=4, offsets=[1, 2, 3])

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 1), (0, 2), (0, 3), (1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 3), (3, 0), (3, 1), (3, 2)]
Matrix:
[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


The circle pattern is quadratic (like `'diag'`) and using a bigger matrix would lead to empty rows and/or columns

In [21]:
idx = spat.get('circle', 4, offsets=[1, 2])

print_matrix(idx, 4, 6)

Sparsity Pattern:
[(0, 2), (0, 3), (1, 0), (1, 3), (2, 0), (2, 1), (3, 1), (3, 2)]
Matrix:
[[0 0 1 1 0 0]
 [1 0 0 1 0 0]
 [1 1 0 0 0 0]
 [0 1 1 0 0 0]]


# `'tril'` and `'triu'`

`triu` only has elements in the upper triangle of a quadratic matrix.

In [22]:
idx = spat.get('triu', n=4, k=0)

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]
Matrix:
[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


`tril` is basically the transposed version of `triu`, vice versa.

In [23]:
idx = spat.get('tril', n=4, k=0)

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 0), (1, 0), (1, 1), (2, 0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2), (3, 3)]
Matrix:
[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]


Usually we use negative `k<0` offsets to make the triangle smaller

In [24]:
idx = spat.get('tril', 4, -1)

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(1, 0), (2, 0), (2, 1), (3, 0), (3, 1), (3, 2)]
Matrix:
[[0 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]]


Positive offsets `k>0` to achieve the opposite effect.

In [25]:
idx = spat.get('tril', 4, 1)

print_matrix(idx, 4, 4)

Sparsity Pattern:
[(0, 0), (0, 1), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3)]
Matrix:
[[1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]
 [1 1 1 1]]
