In [1]:
import sys
sys.path.append('..')

In [2]:
import sparsity_pattern as spat
import tensorflow as tf

# Step 1
We want to create 10x12 matrix

In [3]:
n_rows, n_cols = 10, 12

Create a `'circle'` pattern

In [4]:
n_dim = min(n_rows, n_cols)
idx = spat.get('circle', n_dim, offsets=[1, 2, 4, 5, 7, 8])

print("Sparsity Pattern:")
print(idx)

n_elements = len(idx)
print(f"Number of elements: {n_elements}")

Sparsity Pattern:
[(0, 2), (0, 3), (0, 5), (0, 6), (0, 8), (0, 9), (1, 0), (1, 3), (1, 4), (1, 6), (1, 7), (1, 9), (2, 0), (2, 1), (2, 4), (2, 5), (2, 7), (2, 8), (3, 1), (3, 2), (3, 5), (3, 6), (3, 8), (3, 9), (4, 0), (4, 2), (4, 3), (4, 6), (4, 7), (4, 9), (5, 0), (5, 1), (5, 3), (5, 4), (5, 7), (5, 8), (6, 1), (6, 2), (6, 4), (6, 5), (6, 8), (6, 9), (7, 0), (7, 2), (7, 3), (7, 5), (7, 6), (7, 9), (8, 0), (8, 1), (8, 3), (8, 4), (8, 6), (8, 7), (9, 1), (9, 2), (9, 4), (9, 5), (9, 7), (9, 8)]
Number of elements: 60


# Step 2
Create a sparse tensor, and assign the numbers `[1, 2, ..., 30]`.

In [5]:
idx = tf.convert_to_tensor(idx, dtype=tf.int64)

mat = tf.sparse.SparseTensor(
    dense_shape=(n_rows, n_cols),
    indices=idx,
    values=range(1, n_elements+1)
)

print(tf.sparse.to_dense(mat))

tf.Tensor(
[[ 0  0  1  2  0  3  4  0  5  6  0  0]
 [ 7  0  0  8  9  0 10 11  0 12  0  0]
 [13 14  0  0 15 16  0 17 18  0  0  0]
 [ 0 19 20  0  0 21 22  0 23 24  0  0]
 [25  0 26 27  0  0 28 29  0 30  0  0]
 [31 32  0 33 34  0  0 35 36  0  0  0]
 [ 0 37 38  0 39 40  0  0 41 42  0  0]
 [43  0 44 45  0 46 47  0  0 48  0  0]
 [49 50  0 51 52  0 53 54  0  0  0  0]
 [ 0 55 56  0 57 58  0 59 60  0  0  0]], shape=(10, 12), dtype=int32)
